### PR TITLE
updated lib

### PR DESCRIPTION
**Pull request by Kolyall**

### CODE REVIEW

**Comment by HBiSoft** [comment]
@Kolyall 
Thanks for the pull request and the time spent on doing this. I see you have made a lot of changes. I'm just not sure I want to change the library to kotlin.

**Comment by Kolyall** [comment]
@HBiSoft After convert files from java to kotlin I found a log of nullpointer bugs.

**Comment by HBiSoft** [comment]
@Kolyall 

>After convert files from java to kotlin I found a log of nullpointer bugs.

Can this be replicated in the library as it is now? If so, can you please point to those issues?

**Comment by Kolyall** [comment]
@HBiSoft I can't , because kotlin by default highlight the issues. Seems you don't want to migrate to kotlin due to you don't have experience at it. 
The best way to understand kotlin it just open any java file and make "Convert Java file to Kotlin file" at Android Studio. And then compare changes.
When you will be ready to migrate pls do it for this lib.
Have a nice day.

**Comment by HBiSoft** [comment]
I will not be converting the library to Kotlin.

**Pull request closed without merging**
